<?php

namespace Labs\BackBundle\Repository;

/**
 * BannerImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BannerImageRepository extends \Doctrine\ORM\EntityRepository
{
}
