<?php

namespace Labs\BackBundle\Repository;

/**
 * BestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BestRepository extends \Doctrine\ORM\EntityRepository
{
}
