<?php

namespace Labs\BackBundle\Repository;

/**
 * BestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BestRepository extends \Doctrine\ORM\EntityRepository
{

    public function UpdateStatusTrue($best ,$dossier, $genre)
    {
        $qb = $this->createQueryBuilder('b');
        $qb->leftJoin('b.dossier', 'd');
        $qb->where(
            $qb->expr()->eq('b.id', ':best'),
            $qb->expr()->eq('b.dossier', ':dossier'),
            $qb->expr()->eq('b.genre', ':genre')
        );
        $qb->setParameter(':best', $best);
        $qb->setParameter(':dossier', $dossier);
        $qb->setParameter(':genre', $genre);
        return $qb->getQuery()->getSingleResult();
    }

    public function getBestByDossier($dossier)
    {
        $qb = $this->createQueryBuilder('b');
        $qb->leftJoin('b.dossier', 'd');
        $qb->where(
            $qb->expr()->eq('b.dossier', ':dossier')
        );
        $qb->orderBy('b.top', 'ASC');
        $qb->setParameter(':dossier', $dossier);
        return $qb->getQuery()->getResult();
    }
}
