<?php

namespace Labs\BackBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{

    public function getOneCategory($id)
    {
        $qb = $this->createQueryBuilder('c');
        $qb->where($qb->expr()->eq('c.id', ':id'));
        $qb->setParameter(':id', $id);
        return $qb->getQuery()->getOneOrNullResult();
    }
}
