<?php

namespace Labs\BackBundle\Repository;

use Doctrine\ORM\Query\Expr;

/**
 * DossierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DossierRepository extends \Doctrine\ORM\EntityRepository
{
    public function getOne($id)
    {
        $qb = $this->createQueryBuilder('d');
        $qb->where($qb->expr()->eq('d.id', ':id'));
        $qb->setParameter(':id', $id);
        return $qb->getQuery()->getOneOrNullResult();
    }

    public function getOneAndAssociation($id)
    {
        $qb = $this->createQueryBuilder('d');
        $qb->leftJoin('d.bests','b');
        $qb->addSelect('b');
        $qb->where($qb->expr()->eq('d.id', ':id'));
        $qb->setParameter(':id', $id);
        return $qb->getQuery()->getOneOrNullResult();
    }

    public function findDossierLimit($num = null)
    {
        $qb = $this->createQueryBuilder('d');
        $qb->where($qb->expr()->eq('d.online', 1));
        $qb->orderBy('d.created', 'DESC');
        if( null !== $num ){
            $qb->setMaxResults($num);
        }
        return $qb->getQuery()->getResult();
    }
}
