<?php

namespace Labs\BackBundle\Repository;

/**
 * EventsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventsRepository extends \Doctrine\ORM\EntityRepository
{
    public function getOne($id)
    {
        $qb = $this->createQueryBuilder('e');
        $qb->where($qb->expr()->eq('e.id', ':id'));
        $qb->setParameter(':id', $id);
        return $qb->getQuery()->getOneOrNullResult();
    }
    
    public function getOneAndAssociation($id)
    {
        $qb = $this->createQueryBuilder('e');
        $qb->leftJoin('e.medias','m');
        $qb->addSelect('m');
        $qb->leftJoin('e.category','c');
        $qb->addSelect('c');
        $qb->where($qb->expr()->eq('e.id', ':id'));
        $qb->setParameter(':id', $id);
        return $qb->getQuery()->getOneOrNullResult();
    }
    
    public function findEvents($num = null)
    {
        $qb = $this->createQueryBuilder('e');
        $qb->leftJoin('e.medias','m')
            ->addSelect('m')
            ->leftJoin('e.category', 'c')
            ->addSelect('c')
            ->where($qb->expr()->eq('e.online', 1))
            ->andWhere($qb->expr()->eq('m.actived', 1))
            ->orderBy('e.created', 'DESC');
        if(null !== $num){
          $qb->setMaxResults($num);   
        }
        return $qb->getQuery()->getResult();
    }
}
