<?php

namespace Labs\BackBundle\Repository;

/**
 * PackpageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PackpageRepository extends \Doctrine\ORM\EntityRepository
{
    public function getOne()
    {
        $qb = $this->createQueryBuilder('d');
        return $qb->getQuery()->getOneOrNullResult();
    }
}
