<?php

namespace Labs\BackBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeRepository extends \Doctrine\ORM\EntityRepository
{

    public function getOne($id)
    {
        $qb = $this->createQueryBuilder('t');
        $qb->where($qb->expr()->eq('t.id', ':id'));
        $qb->setParameter(':id', $id);
        return $qb->getQuery()->getOneOrNullResult();
    }

    public function getOneArgument($type_id)
    {
        $qb = $this->createQueryBuilder('t');
        $qb->where($qb->expr()->eq('t.id', ':id'));
        $qb->setParameter(':id', $type_id);
        return $qb->getQuery()->getOneOrNullResult();
    }

    public function findMediaGroupBy($dossier)
    {
        $qb = $this->createQueryBuilder('t');
        $qb->leftJoin('t.medias','m')
            ->addSelect('m')
            ->leftJoin('m.dossier', 'd')
            ->addSelect('d');
        $qb->where($qb->expr()->eq('m.dossier', ':dossier'))
            ->setParameter(':dossier', $dossier);
        return $qb->getQuery()->getResult();
    }

    public function findDossierAndMediaForType()
    {
        $qb = $this->createQueryBuilder('t');
        $qb->leftJoin('t.medias', 'm')
            ->addSelect('m')
            ->leftJoin('m.dossier','d')
            ->addSelect('d')
            ->where($qb->expr()->eq('m.actived', 1))
            ->andWhere($qb->expr()->eq('d.online', 1))
            ->orderBy('d.created', 'DESC')
            ->setMaxResults(6);
        return $qb->getQuery()->getResult();
    }
}
