imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    gallery_directory: '%kernel.root_dir%/../web/uploads/gallery'

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   ~
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping: true
                mappings:
                    gedmo_tree:
                        type: annotation
                        prefix: Gedmo\Tree\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"
                        alias : GedmoTree # (optional) it will default to the name set for the mapping
                        is_bundle: false


stof_doctrine_extensions:
    orm:
        default:
            sluggable: true

doctrine_migrations:
    dir_name: "%kernel.root_dir%/DoctrineMigrations"
    namespace: Application\Migrations
    table_name: migration_versions
    name: Application Migrations

ivory_ck_editor:
    default_config: my_custom_config
    configs:
        my_custom_config:
            language: "%locale%"
            toolbar: [ [ 'Bold','Italic','Underline' ], [ 'NumberedList','BulletedList','-','Outdent','Indent','-','-','JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock' ], '/', [ 'Maximize' ] ]
            uiColor:   "#FCFCFC"
            forcePasteAsPlainText: true


vich_uploader:
    db_driver: orm # or mongodb or propel or phpcr
    twig:      true
    storage:   file_system # or gaufrette or flysystem
    mappings:
        team_image:
            uri_prefix:         /uploads/bestman
            upload_destination: "%kernel.root_dir%/../web/uploads/bestman"
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
            namer:              vich_uploader.namer_uniqid

        banner_image:
            uri_prefix:         /uploads/banners
            upload_destination: "%kernel.root_dir%/../web/uploads/banners"
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
            namer:              vich_uploader.namer_uniqid

        partner_image:
            uri_prefix:         /uploads/partner
            upload_destination: "%kernel.root_dir%/../web/uploads/partner"
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
            namer:              vich_uploader.namer_uniqid

        banner_image_page:
            uri_prefix:         /uploads/pages
            upload_destination: "%kernel.root_dir%/../web/uploads/pages"
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
            namer:              vich_uploader.namer_uniqid

        dossier_image_page:
            uri_prefix:         /uploads/dossier
            upload_destination: "%kernel.root_dir%/../web/uploads/dossier"
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
            namer:              vich_uploader.namer_uniqid
#liip_imagine upload crop image

liip_imagine:
    resolvers:
       default:
          web_path: ~

    filter_sets:
        cache: ~
        my_thumb_best:
            quality: 75
            filters:
                thumbnail: { size: [100, 100], mode: outbound }
                watermark :
                    image: Resources/data/logo-dark.png
                    size: 0.2
                    position: bottomright


        my_thumb_admin_gallery:
            quality: 60
            filters:
                thumbnail: { size: [218, 145], mode: outbound }
                watermark :
                    image: Resources/data/logo-dark.png
                    size: 0.2
                    position: bottomright

        photo_dg:
            quality: 100
            filters:
                thumbnail: { size: [430, 300], mode: outbound }

        image_profolio:
            quality: 100
            filters:
                thumbnail: { size: [400, 300], mode: outbound }
                watermark :
                    image: Resources/data/logo-dark.png
                    size: 0.2
                    position: bottomright

        image_profolio_full:
            quality: 100
            filters:
                relative_resize: { widen: 980 }
                watermark :
                    image: Resources/data/logo-dark.png
                    size: 0.2
                    position: bottomright

        page_pckage:
            quality: 100
            filters:
                relative_resize: { widen: 745 }

        logo_partenaire:
            quality: 100
            filters:
                thumbnail: { size: [142, 107], mode: outbound }

        citation_thumb:
            quality: 100
            filters:
                thumbnail: { size: [64, 64], mode: outbound }

        slide:
            quality: 100
            filters:
                thumbnail: { size: [980, 653], mode: outbound }
                watermark :
                    image: Resources/data/logo-dark.png
                    size: 0.2
                    position: bottomright

        slide_wedding:
            quality: 100
            filters:
                thumbnail: { size: [1140, 500], mode: outbound }
                watermark :
                    image: Resources/data/logo-dark.png
                    size: 0.2
                    position: bottomright

        slide_wedding_view:
            quality: 100
            filters:
                thumbnail: { size: [1500, 833], mode: outbound }
                watermark :
                    image: Resources/data/logo-dark.png
                    size: 0.2
                    position: bottomright

        slide_wedding_view_page:
            quality: 100
            filters:
                relative_resize: { widen: 1500  }
                watermark :
                    image: Resources/data/logo-dark.png
                    size: 0.2
                    position: bottomright


        slide_wedding_view_thumb:
            quality: 100
            filters:
                thumbnail: { size: [400, 300], mode: outbound }
                watermark :
                    image: Resources/data/logo-dark.png
                    size: 0.2
                    position: bottomright

        wedding_couple:
            quality: 100
            filters:
                thumbnail: { size: [300, 300], mode: outbound }


        best_man:
            quality: 100
            filters:
                thumbnail: { size: [430, 300], mode: outbound }

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: KnpPaginatorBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig     # sliding pagination controls template
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template