labs_front:
    resource: "@LabsFrontBundle/Controller/"
    type:     annotation
    prefix:   /

labs_back:
    resource: "@LabsBackBundle/Controller/"
    type:     annotation
    prefix:   /admin

labs_template:
    resource: "@LabsTemplateBundle/Controller/"
    type:     annotation

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"